### ISSUE TITLE
Some question about preprocess

### ISSUE THREAD

**Issue by WSM123123** [quzefan/LuSh-NeRF#2]
Hi, your work is great, but I have a question. How is this scaleup operation implemented? It seems that manual adjustment is required through histogram and gamma correction.

**Comment by quzefan** [comment]
Thanks for your interest to our work. 
Yes, our work need to do the manual adjustment to the input images. We adjusted the color constrast by the histogram first, and then enhanced the pixel intensity.
The histogram preprocess code is based on the cv2.createCLAHE() function. You can get more details of this function at <a href="https://docs.opencv.org/4.x/d5/daf/tutorial_py_histogram_equalization.html">here</a>. For gamma correction, you can just use np.power() function and do the clamp operation.
