### ISSUE TITLE
The preprocess of the training images?

### ISSUE THREAD

**Issue by Wangzs0118** [quzefan/LuSh-NeRF#3]
Dear author, firstly, congratulations on being accepted to NeurIPS 2024! Your work is truly outstanding!
In your paper you proposed that '.Before training, the input images are up-scaled by gamma adjustment and histogram
equalization', how this preprocess achieves in detail? Is there any pre-trained model used?

**Comment by quzefan** [comment]
Thanks for your interest to our works.
For the preprocess method, your can get more information in issue #2.
The corresponding code is at [here](https://github.com/quzefan/LuSh-NeRF/blob/fcc31b270ce2f73ed871686722e87dcc74cfb5c6/data_utils/load_llff.py#L109). No pre-trained model is utilized in our implementation.
